#pragma once

#define RSA_KEY_SIZE_BITS       1024
#define RSA_PUBLIC_KEY_SIZE     RSA_KEY_SIZE_BITS / 8
#define RSA_PRIVATE_KEY_SIZE    RSA_PUBLIC_KEY_SIZE * 2
#define RSA_MODULUS_KEY_SIZE    RSA_PUBLIC_KEY_SIZE * 2
#define RSA_ENCODE_BLOCK_SIZE   ((2 * RSA_KEY_SIZE_BITS) - 1) / 8
#define RSA_DECODE_BLOCK_SIZE   RSA_PRIVATE_KEY_SIZE
